/* Generated by Yosys 0.51+46 (git sha1 8bde6ac17, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module \$paramod$1285c1740f954ea74f58bd88e5bc92df4339bc55\MBIST_Controller (clk, rst_n, start_bist, bist_done, bist_pass, csb0, web0, addr0, din0, dout0);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire [2:0] _158_;
  wire [9:0] _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  output [8:0] addr0;
  wire [8:0] addr0;
  wire [9:0] addr_cnt;
  output bist_done;
  wire bist_done;
  output bist_pass;
  wire bist_pass;
  input clk;
  wire clk;
  output csb0;
  wire csb0;
  output [31:0] din0;
  wire [31:0] din0;
  input [31:0] dout0;
  wire [31:0] dout0;
  input rst_n;
  wire rst_n;
  input start_bist;
  wire start_bist;
  wire [2:0] state;
  output web0;
  wire web0;
  sky130_fd_sc_hd__clkinv_1 _164_ (
    .A(addr_cnt[8]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(addr_cnt[6]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _166_ (
    .A(addr_cnt[7]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor2_1 _167_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor3_1 _168_ (
    .A(state[1]),
    .B(state[0]),
    .C(state[2]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o21ai_0 _169_ (
    .A1(state[1]),
    .A2(state[0]),
    .B1(state[2]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2b_1 _170_ (
    .A(_045_),
    .B_N(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2b_1 _171_ (
    .A_N(_045_),
    .B(_046_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _172_ (
    .A(rst_n),
    .B(_047_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _173_ (
    .A0(addr_cnt[0]),
    .A1(addr0[0]),
    .S(_049_),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _174_ (
    .A0(addr_cnt[1]),
    .A1(addr0[1]),
    .S(_049_),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _175_ (
    .A0(addr_cnt[2]),
    .A1(addr0[2]),
    .S(_049_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _176_ (
    .A0(addr_cnt[3]),
    .A1(addr0[3]),
    .S(_049_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _177_ (
    .A0(addr_cnt[4]),
    .A1(addr0[4]),
    .S(_049_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _178_ (
    .A0(addr_cnt[5]),
    .A1(addr0[5]),
    .S(_049_),
    .X(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _179_ (
    .A(addr0[6]),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o21ai_0 _180_ (
    .A1(_042_),
    .A2(_049_),
    .B1(_050_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _181_ (
    .A(addr0[7]),
    .B(_049_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o21ai_0 _182_ (
    .A1(_043_),
    .A2(_049_),
    .B1(_051_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(addr0[8]),
    .B(_049_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o21ai_0 _184_ (
    .A1(_041_),
    .A2(_049_),
    .B1(_052_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _185_ (
    .A(state[0]),
    .SLEEP(state[1]),
    .X(_053_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _186_ (
    .A(_053_),
    .SLEEP(state[2]),
    .X(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _187_ (
    .A(rst_n),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(din0[0]),
    .B(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand4b_1 _189_ (
    .A_N(state[2]),
    .B(rst_n),
    .C(state[1]),
    .D(state[0]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nand2_1 _190_ (
    .A(_056_),
    .B(_057_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2_1 _191_ (
    .A(din0[1]),
    .B(_055_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(_057_),
    .B(_058_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _193_ (
    .A(din0[2]),
    .B(_055_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_1 _194_ (
    .A(_057_),
    .B(_059_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(din0[3]),
    .B(_055_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _196_ (
    .A(_057_),
    .B(_060_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(din0[4]),
    .B(_055_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _198_ (
    .A(_057_),
    .B(_061_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(din0[5]),
    .B(_055_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _200_ (
    .A(_057_),
    .B(_062_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(din0[6]),
    .B(_055_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _202_ (
    .A(_057_),
    .B(_063_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(din0[7]),
    .B(_055_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _204_ (
    .A(_057_),
    .B(_064_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _205_ (
    .A(din0[8]),
    .B(_055_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(_057_),
    .B(_065_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _207_ (
    .A(din0[9]),
    .B(_055_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _208_ (
    .A(_057_),
    .B(_066_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(din0[10]),
    .B(_055_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _210_ (
    .A(_057_),
    .B(_067_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(din0[11]),
    .B(_055_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(_057_),
    .B(_068_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(din0[12]),
    .B(_055_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(_057_),
    .B(_069_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(din0[13]),
    .B(_055_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(_057_),
    .B(_070_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _217_ (
    .A(din0[14]),
    .B(_055_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(_057_),
    .B(_071_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _219_ (
    .A(din0[15]),
    .B(_055_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _220_ (
    .A(_057_),
    .B(_072_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _221_ (
    .A(din0[16]),
    .B(_055_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nand2_1 _222_ (
    .A(_057_),
    .B(_073_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _223_ (
    .A(din0[17]),
    .B(_055_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_057_),
    .B(_074_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(din0[18]),
    .B(_055_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _226_ (
    .A(_057_),
    .B(_075_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(din0[19]),
    .B(_055_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _228_ (
    .A(_057_),
    .B(_076_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _229_ (
    .A(din0[20]),
    .B(_055_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(_057_),
    .B(_077_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(din0[21]),
    .B(_055_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _232_ (
    .A(_057_),
    .B(_078_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(din0[22]),
    .B(_055_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(_057_),
    .B(_079_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _235_ (
    .A(din0[23]),
    .B(_055_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(_057_),
    .B(_080_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(din0[24]),
    .B(_055_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _238_ (
    .A(_057_),
    .B(_081_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(din0[25]),
    .B(_055_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(_057_),
    .B(_082_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _241_ (
    .A(din0[26]),
    .B(_055_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(_057_),
    .B(_083_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(din0[27]),
    .B(_055_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _244_ (
    .A(_057_),
    .B(_084_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(din0[28]),
    .B(_055_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(_057_),
    .B(_085_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _247_ (
    .A(din0[29]),
    .B(_055_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(_057_),
    .B(_086_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(din0[30]),
    .B(_055_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _250_ (
    .A(_057_),
    .B(_087_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(din0[31]),
    .B(_055_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(_057_),
    .B(_088_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__and3_1 _253_ (
    .A(addr_cnt[1]),
    .B(addr_cnt[2]),
    .C(addr_cnt[0]),
    .X(_089_)
  );
  sky130_fd_sc_hd__and2_0 _254_ (
    .A(addr_cnt[3]),
    .B(addr_cnt[4]),
    .X(_090_)
  );
  sky130_fd_sc_hd__nand3_1 _255_ (
    .A(addr_cnt[5]),
    .B(_089_),
    .C(_090_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand4_1 _256_ (
    .A(addr_cnt[5]),
    .B(addr_cnt[6]),
    .C(_089_),
    .D(_090_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _257_ (
    .A(_043_),
    .B(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor4_1 _258_ (
    .A(_041_),
    .B(_043_),
    .C(addr_cnt[9]),
    .D(_092_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _259_ (
    .A(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor2_1 _260_ (
    .A(state[0]),
    .B(_094_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(state[2]),
    .B(_044_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a21oi_1 _262_ (
    .A1(state[0]),
    .A2(_094_),
    .B1(state[2]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__a21boi_0 _263_ (
    .A1(state[1]),
    .A2(_098_),
    .B1_N(_097_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nand2_1 _264_ (
    .A(start_bist),
    .B(_045_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(state[2]),
    .B(_053_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand2_1 _266_ (
    .A(state[1]),
    .B(state[2]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__and3_1 _267_ (
    .A(state[1]),
    .B(state[0]),
    .C(state[2]),
    .X(_103_)
  );
  sky130_fd_sc_hd__a21oi_1 _268_ (
    .A1(_054_),
    .A2(_095_),
    .B1(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o211ai_1 _269_ (
    .A1(_096_),
    .A2(_099_),
    .B1(_100_),
    .C1(_104_),
    .Y(_158_[0])
  );
  sky130_fd_sc_hd__a22oi_1 _270_ (
    .A1(_054_),
    .A2(_094_),
    .B1(_098_),
    .B2(state[1]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nand2_1 _271_ (
    .A(_102_),
    .B(_105_),
    .Y(_158_[1])
  );
  sky130_fd_sc_hd__nor2_1 _272_ (
    .A(_053_),
    .B(_098_),
    .Y(_158_[2])
  );
  sky130_fd_sc_hd__a21oi_1 _273_ (
    .A1(start_bist),
    .A2(_046_),
    .B1(_047_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _274_ (
    .A(addr_cnt[0]),
    .B(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__o21ai_0 _275_ (
    .A1(addr_cnt[0]),
    .A2(_048_),
    .B1(_107_),
    .Y(_159_[0])
  );
  sky130_fd_sc_hd__nor2_1 _276_ (
    .A(addr_cnt[1]),
    .B(addr_cnt[0]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21oi_1 _277_ (
    .A1(addr_cnt[1]),
    .A2(addr_cnt[0]),
    .B1(_048_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a21oi_1 _278_ (
    .A1(addr_cnt[1]),
    .A2(_106_),
    .B1(_109_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nor2_1 _279_ (
    .A(_108_),
    .B(_110_),
    .Y(_159_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _280_ (
    .A1(addr_cnt[1]),
    .A2(addr_cnt[0]),
    .B1(addr_cnt[2]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(addr_cnt[2]),
    .B(_106_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__o31ai_1 _282_ (
    .A1(_048_),
    .A2(_089_),
    .A3(_111_),
    .B1(_112_),
    .Y(_159_[2])
  );
  sky130_fd_sc_hd__a21oi_1 _283_ (
    .A1(_047_),
    .A2(_089_),
    .B1(addr_cnt[3]),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand3_1 _284_ (
    .A(addr_cnt[3]),
    .B(_047_),
    .C(_089_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(_100_),
    .B(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nor2_1 _286_ (
    .A(_113_),
    .B(_115_),
    .Y(_159_[3])
  );
  sky130_fd_sc_hd__nand3_1 _287_ (
    .A(addr_cnt[4]),
    .B(_100_),
    .C(_114_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__o21ai_0 _288_ (
    .A1(addr_cnt[4]),
    .A2(_114_),
    .B1(_116_),
    .Y(_159_[4])
  );
  sky130_fd_sc_hd__a21oi_1 _289_ (
    .A1(_089_),
    .A2(_090_),
    .B1(addr_cnt[5]),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a22oi_1 _290_ (
    .A1(_047_),
    .A2(_091_),
    .B1(_106_),
    .B2(addr_cnt[5]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nor2_1 _291_ (
    .A(_117_),
    .B(_118_),
    .Y(_159_[5])
  );
  sky130_fd_sc_hd__a22oi_1 _292_ (
    .A1(_047_),
    .A2(_092_),
    .B1(_106_),
    .B2(addr_cnt[6]),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a21oi_1 _293_ (
    .A1(_042_),
    .A2(_091_),
    .B1(_119_),
    .Y(_159_[6])
  );
  sky130_fd_sc_hd__nor2_1 _294_ (
    .A(_048_),
    .B(_093_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a21oi_1 _295_ (
    .A1(addr_cnt[7]),
    .A2(_106_),
    .B1(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a21oi_1 _296_ (
    .A1(_043_),
    .A2(_092_),
    .B1(_121_),
    .Y(_159_[7])
  );
  sky130_fd_sc_hd__a21oi_1 _297_ (
    .A1(_047_),
    .A2(_093_),
    .B1(addr_cnt[8]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand3_1 _298_ (
    .A(addr_cnt[8]),
    .B(_047_),
    .C(_093_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nand2_1 _299_ (
    .A(_100_),
    .B(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_1 _300_ (
    .A(_122_),
    .B(_124_),
    .Y(_159_[8])
  );
  sky130_fd_sc_hd__nand3_1 _301_ (
    .A(addr_cnt[9]),
    .B(_100_),
    .C(_123_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__o21ai_0 _302_ (
    .A1(state[0]),
    .A2(state[2]),
    .B1(_046_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o21ai_0 _303_ (
    .A1(_095_),
    .A2(_126_),
    .B1(_125_),
    .Y(_159_[9])
  );
  sky130_fd_sc_hd__nand2_1 _304_ (
    .A(web0),
    .B(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor3b_1 _305_ (
    .A(state[0]),
    .B(state[2]),
    .C_N(state[1]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21oi_1 _306_ (
    .A1(state[2]),
    .A2(_044_),
    .B1(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand3_1 _307_ (
    .A(_101_),
    .B(_127_),
    .C(_129_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _308_ (
    .A(csb0),
    .B(_048_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _309_ (
    .A(_101_),
    .B(_130_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__a21oi_1 _310_ (
    .A1(start_bist),
    .A2(_045_),
    .B1(bist_pass),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand4_1 _311_ (
    .A(dout0[28]),
    .B(dout0[29]),
    .C(dout0[30]),
    .D(dout0[31]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand4_1 _312_ (
    .A(dout0[24]),
    .B(dout0[25]),
    .C(dout0[26]),
    .D(dout0[27]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nor3_1 _313_ (
    .A(_097_),
    .B(_132_),
    .C(_133_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand4_1 _314_ (
    .A(dout0[4]),
    .B(dout0[5]),
    .C(dout0[6]),
    .D(dout0[7]),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand4_1 _315_ (
    .A(dout0[1]),
    .B(dout0[0]),
    .C(dout0[2]),
    .D(dout0[3]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor2_1 _316_ (
    .A(_135_),
    .B(_136_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand4_1 _317_ (
    .A(dout0[12]),
    .B(dout0[13]),
    .C(dout0[14]),
    .D(dout0[15]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand4_1 _318_ (
    .A(dout0[8]),
    .B(dout0[9]),
    .C(dout0[10]),
    .D(dout0[11]),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand4_1 _319_ (
    .A(dout0[20]),
    .B(dout0[21]),
    .C(dout0[22]),
    .D(dout0[23]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand4_1 _320_ (
    .A(dout0[16]),
    .B(dout0[17]),
    .C(dout0[18]),
    .D(dout0[19]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__nor4_1 _321_ (
    .A(_138_),
    .B(_139_),
    .C(_140_),
    .D(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a31oi_1 _322_ (
    .A1(_134_),
    .A2(_137_),
    .A3(_142_),
    .B1(_129_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor4_1 _323_ (
    .A(dout0[28]),
    .B(dout0[29]),
    .C(dout0[30]),
    .D(dout0[31]),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor4_1 _324_ (
    .A(dout0[24]),
    .B(dout0[25]),
    .C(dout0[26]),
    .D(dout0[27]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor4_1 _325_ (
    .A(dout0[4]),
    .B(dout0[5]),
    .C(dout0[6]),
    .D(dout0[7]),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nor4_1 _326_ (
    .A(dout0[1]),
    .B(dout0[0]),
    .C(dout0[2]),
    .D(dout0[3]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__nand2_1 _327_ (
    .A(_146_),
    .B(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor4_1 _328_ (
    .A(dout0[20]),
    .B(dout0[21]),
    .C(dout0[22]),
    .D(dout0[23]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor4_1 _329_ (
    .A(dout0[16]),
    .B(dout0[17]),
    .C(dout0[18]),
    .D(dout0[19]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(_149_),
    .B(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor4_1 _331_ (
    .A(dout0[12]),
    .B(dout0[13]),
    .C(dout0[14]),
    .D(dout0[15]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor4_1 _332_ (
    .A(dout0[8]),
    .B(dout0[9]),
    .C(dout0[10]),
    .D(dout0[11]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(_152_),
    .B(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__nor3_1 _334_ (
    .A(_148_),
    .B(_151_),
    .C(_154_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nand4_1 _335_ (
    .A(_128_),
    .B(_144_),
    .C(_145_),
    .D(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a21oi_1 _336_ (
    .A1(_143_),
    .A2(_156_),
    .B1(_131_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(bist_done),
    .B(_100_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(_101_),
    .B(_157_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__dfrtp_1 _339_ (
    .CLK(clk),
    .D(_163_),
    .Q(bist_done),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _340_ (
    .CLK(clk),
    .D(_162_),
    .Q(bist_pass),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _341_ (
    .CLK(clk),
    .D(_161_),
    .Q(csb0),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _342_ (
    .CLK(clk),
    .D(_160_),
    .Q(web0),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _343_ (
    .CLK(clk),
    .D(_000_),
    .Q(addr0[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _344_ (
    .CLK(clk),
    .D(_001_),
    .Q(addr0[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _345_ (
    .CLK(clk),
    .D(_002_),
    .Q(addr0[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _346_ (
    .CLK(clk),
    .D(_003_),
    .Q(addr0[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _347_ (
    .CLK(clk),
    .D(_004_),
    .Q(addr0[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _348_ (
    .CLK(clk),
    .D(_005_),
    .Q(addr0[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _349_ (
    .CLK(clk),
    .D(_006_),
    .Q(addr0[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _350_ (
    .CLK(clk),
    .D(_007_),
    .Q(addr0[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _351_ (
    .CLK(clk),
    .D(_008_),
    .Q(addr0[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _352_ (
    .CLK(clk),
    .D(_009_),
    .Q(din0[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _353_ (
    .CLK(clk),
    .D(_020_),
    .Q(din0[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _354_ (
    .CLK(clk),
    .D(_031_),
    .Q(din0[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _355_ (
    .CLK(clk),
    .D(_034_),
    .Q(din0[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _356_ (
    .CLK(clk),
    .D(_035_),
    .Q(din0[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _357_ (
    .CLK(clk),
    .D(_036_),
    .Q(din0[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _358_ (
    .CLK(clk),
    .D(_037_),
    .Q(din0[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _359_ (
    .CLK(clk),
    .D(_038_),
    .Q(din0[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _360_ (
    .CLK(clk),
    .D(_039_),
    .Q(din0[8])
  );
  sky130_fd_sc_hd__dfxtp_1 _361_ (
    .CLK(clk),
    .D(_040_),
    .Q(din0[9])
  );
  sky130_fd_sc_hd__dfxtp_1 _362_ (
    .CLK(clk),
    .D(_010_),
    .Q(din0[10])
  );
  sky130_fd_sc_hd__dfxtp_1 _363_ (
    .CLK(clk),
    .D(_011_),
    .Q(din0[11])
  );
  sky130_fd_sc_hd__dfxtp_1 _364_ (
    .CLK(clk),
    .D(_012_),
    .Q(din0[12])
  );
  sky130_fd_sc_hd__dfxtp_1 _365_ (
    .CLK(clk),
    .D(_013_),
    .Q(din0[13])
  );
  sky130_fd_sc_hd__dfxtp_1 _366_ (
    .CLK(clk),
    .D(_014_),
    .Q(din0[14])
  );
  sky130_fd_sc_hd__dfxtp_1 _367_ (
    .CLK(clk),
    .D(_015_),
    .Q(din0[15])
  );
  sky130_fd_sc_hd__dfxtp_1 _368_ (
    .CLK(clk),
    .D(_016_),
    .Q(din0[16])
  );
  sky130_fd_sc_hd__dfxtp_1 _369_ (
    .CLK(clk),
    .D(_017_),
    .Q(din0[17])
  );
  sky130_fd_sc_hd__dfxtp_1 _370_ (
    .CLK(clk),
    .D(_018_),
    .Q(din0[18])
  );
  sky130_fd_sc_hd__dfxtp_1 _371_ (
    .CLK(clk),
    .D(_019_),
    .Q(din0[19])
  );
  sky130_fd_sc_hd__dfxtp_1 _372_ (
    .CLK(clk),
    .D(_021_),
    .Q(din0[20])
  );
  sky130_fd_sc_hd__dfxtp_1 _373_ (
    .CLK(clk),
    .D(_022_),
    .Q(din0[21])
  );
  sky130_fd_sc_hd__dfxtp_1 _374_ (
    .CLK(clk),
    .D(_023_),
    .Q(din0[22])
  );
  sky130_fd_sc_hd__dfxtp_1 _375_ (
    .CLK(clk),
    .D(_024_),
    .Q(din0[23])
  );
  sky130_fd_sc_hd__dfxtp_1 _376_ (
    .CLK(clk),
    .D(_025_),
    .Q(din0[24])
  );
  sky130_fd_sc_hd__dfxtp_1 _377_ (
    .CLK(clk),
    .D(_026_),
    .Q(din0[25])
  );
  sky130_fd_sc_hd__dfxtp_1 _378_ (
    .CLK(clk),
    .D(_027_),
    .Q(din0[26])
  );
  sky130_fd_sc_hd__dfxtp_1 _379_ (
    .CLK(clk),
    .D(_028_),
    .Q(din0[27])
  );
  sky130_fd_sc_hd__dfxtp_1 _380_ (
    .CLK(clk),
    .D(_029_),
    .Q(din0[28])
  );
  sky130_fd_sc_hd__dfxtp_1 _381_ (
    .CLK(clk),
    .D(_030_),
    .Q(din0[29])
  );
  sky130_fd_sc_hd__dfxtp_1 _382_ (
    .CLK(clk),
    .D(_032_),
    .Q(din0[30])
  );
  sky130_fd_sc_hd__dfxtp_1 _383_ (
    .CLK(clk),
    .D(_033_),
    .Q(din0[31])
  );
  sky130_fd_sc_hd__dfrtp_1 _384_ (
    .CLK(clk),
    .D(_159_[0]),
    .Q(addr_cnt[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _385_ (
    .CLK(clk),
    .D(_159_[1]),
    .Q(addr_cnt[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _386_ (
    .CLK(clk),
    .D(_159_[2]),
    .Q(addr_cnt[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _387_ (
    .CLK(clk),
    .D(_159_[3]),
    .Q(addr_cnt[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _388_ (
    .CLK(clk),
    .D(_159_[4]),
    .Q(addr_cnt[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _389_ (
    .CLK(clk),
    .D(_159_[5]),
    .Q(addr_cnt[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _390_ (
    .CLK(clk),
    .D(_159_[6]),
    .Q(addr_cnt[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _391_ (
    .CLK(clk),
    .D(_159_[7]),
    .Q(addr_cnt[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _392_ (
    .CLK(clk),
    .D(_159_[8]),
    .Q(addr_cnt[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _393_ (
    .CLK(clk),
    .D(_159_[9]),
    .Q(addr_cnt[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _394_ (
    .CLK(clk),
    .D(_158_[0]),
    .Q(state[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _395_ (
    .CLK(clk),
    .D(_158_[1]),
    .Q(state[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _396_ (
    .CLK(clk),
    .D(_158_[2]),
    .Q(state[2]),
    .RESET_B(rst_n)
  );
endmodule

module SRAM_MBIST_WRAPPER(clk, rst_n, mbist_enable, start_bist, bist_done, bist_pass, csb0_ext, web0_ext, addr0_ext, din0_ext, dout0_ext, wcr_in, wcr_out, wdr_in, wdr_out, wbr);
  wire [8:0] addr0_bist;
  input [8:0] addr0_ext;
  wire [8:0] addr0_ext;
  wire [8:0] addr0_mux;
  output bist_done;
  wire bist_done;
  output bist_pass;
  wire bist_pass;
  input clk;
  wire clk;
  wire csb0_bist;
  input csb0_ext;
  wire csb0_ext;
  wire csb0_mux;
  wire [31:0] din0_bist;
  input [31:0] din0_ext;
  wire [31:0] din0_ext;
  wire [31:0] din0_mux;
  output [31:0] dout0_ext;
  wire [31:0] dout0_ext;
  wire [31:0] dout0_sram;
  input mbist_enable;
  wire mbist_enable;
  input rst_n;
  wire rst_n;
  input start_bist;
  wire start_bist;
  output [63:0] wbr;
  wire [63:0] wbr;
  input [7:0] wcr_in;
  wire [7:0] wcr_in;
  output [7:0] wcr_out;
  wire [7:0] wcr_out;
  input [31:0] wdr_in;
  wire [31:0] wdr_in;
  output [31:0] wdr_out;
  wire [31:0] wdr_out;
  wire web0_bist;
  input web0_ext;
  wire web0_ext;
  wire web0_mux;
  sky130_fd_sc_hd__mux2_1 _000_ (
    .A0(csb0_ext),
    .A1(csb0_bist),
    .S(mbist_enable),
    .X(csb0_mux)
  );
  sky130_fd_sc_hd__mux2_1 _001_ (
    .A0(web0_ext),
    .A1(web0_bist),
    .S(mbist_enable),
    .X(web0_mux)
  );
  sky130_fd_sc_hd__mux2_1 _002_ (
    .A0(addr0_ext[0]),
    .A1(addr0_bist[0]),
    .S(mbist_enable),
    .X(addr0_mux[0])
  );
  sky130_fd_sc_hd__mux2_1 _003_ (
    .A0(addr0_ext[1]),
    .A1(addr0_bist[1]),
    .S(mbist_enable),
    .X(addr0_mux[1])
  );
  sky130_fd_sc_hd__mux2_1 _004_ (
    .A0(addr0_ext[2]),
    .A1(addr0_bist[2]),
    .S(mbist_enable),
    .X(addr0_mux[2])
  );
  sky130_fd_sc_hd__mux2_1 _005_ (
    .A0(addr0_ext[3]),
    .A1(addr0_bist[3]),
    .S(mbist_enable),
    .X(addr0_mux[3])
  );
  sky130_fd_sc_hd__mux2_1 _006_ (
    .A0(addr0_ext[4]),
    .A1(addr0_bist[4]),
    .S(mbist_enable),
    .X(addr0_mux[4])
  );
  sky130_fd_sc_hd__mux2_1 _007_ (
    .A0(addr0_ext[5]),
    .A1(addr0_bist[5]),
    .S(mbist_enable),
    .X(addr0_mux[5])
  );
  sky130_fd_sc_hd__mux2_1 _008_ (
    .A0(addr0_ext[6]),
    .A1(addr0_bist[6]),
    .S(mbist_enable),
    .X(addr0_mux[6])
  );
  sky130_fd_sc_hd__mux2_1 _009_ (
    .A0(addr0_ext[7]),
    .A1(addr0_bist[7]),
    .S(mbist_enable),
    .X(addr0_mux[7])
  );
  sky130_fd_sc_hd__mux2_1 _010_ (
    .A0(addr0_ext[8]),
    .A1(addr0_bist[8]),
    .S(mbist_enable),
    .X(addr0_mux[8])
  );
  sky130_fd_sc_hd__mux2_1 _011_ (
    .A0(din0_ext[0]),
    .A1(din0_bist[0]),
    .S(mbist_enable),
    .X(din0_mux[0])
  );
  sky130_fd_sc_hd__mux2_1 _012_ (
    .A0(din0_ext[1]),
    .A1(din0_bist[1]),
    .S(mbist_enable),
    .X(din0_mux[1])
  );
  sky130_fd_sc_hd__mux2_1 _013_ (
    .A0(din0_ext[2]),
    .A1(din0_bist[2]),
    .S(mbist_enable),
    .X(din0_mux[2])
  );
  sky130_fd_sc_hd__mux2_1 _014_ (
    .A0(din0_ext[3]),
    .A1(din0_bist[3]),
    .S(mbist_enable),
    .X(din0_mux[3])
  );
  sky130_fd_sc_hd__mux2_1 _015_ (
    .A0(din0_ext[4]),
    .A1(din0_bist[4]),
    .S(mbist_enable),
    .X(din0_mux[4])
  );
  sky130_fd_sc_hd__mux2_1 _016_ (
    .A0(din0_ext[5]),
    .A1(din0_bist[5]),
    .S(mbist_enable),
    .X(din0_mux[5])
  );
  sky130_fd_sc_hd__mux2_1 _017_ (
    .A0(din0_ext[6]),
    .A1(din0_bist[6]),
    .S(mbist_enable),
    .X(din0_mux[6])
  );
  sky130_fd_sc_hd__mux2_1 _018_ (
    .A0(din0_ext[7]),
    .A1(din0_bist[7]),
    .S(mbist_enable),
    .X(din0_mux[7])
  );
  sky130_fd_sc_hd__mux2_1 _019_ (
    .A0(din0_ext[8]),
    .A1(din0_bist[8]),
    .S(mbist_enable),
    .X(din0_mux[8])
  );
  sky130_fd_sc_hd__mux2_1 _020_ (
    .A0(din0_ext[9]),
    .A1(din0_bist[9]),
    .S(mbist_enable),
    .X(din0_mux[9])
  );
  sky130_fd_sc_hd__mux2_1 _021_ (
    .A0(din0_ext[10]),
    .A1(din0_bist[10]),
    .S(mbist_enable),
    .X(din0_mux[10])
  );
  sky130_fd_sc_hd__mux2_1 _022_ (
    .A0(din0_ext[11]),
    .A1(din0_bist[11]),
    .S(mbist_enable),
    .X(din0_mux[11])
  );
  sky130_fd_sc_hd__mux2_1 _023_ (
    .A0(din0_ext[12]),
    .A1(din0_bist[12]),
    .S(mbist_enable),
    .X(din0_mux[12])
  );
  sky130_fd_sc_hd__mux2_1 _024_ (
    .A0(din0_ext[13]),
    .A1(din0_bist[13]),
    .S(mbist_enable),
    .X(din0_mux[13])
  );
  sky130_fd_sc_hd__mux2_1 _025_ (
    .A0(din0_ext[14]),
    .A1(din0_bist[14]),
    .S(mbist_enable),
    .X(din0_mux[14])
  );
  sky130_fd_sc_hd__mux2_1 _026_ (
    .A0(din0_ext[15]),
    .A1(din0_bist[15]),
    .S(mbist_enable),
    .X(din0_mux[15])
  );
  sky130_fd_sc_hd__mux2_1 _027_ (
    .A0(din0_ext[16]),
    .A1(din0_bist[16]),
    .S(mbist_enable),
    .X(din0_mux[16])
  );
  sky130_fd_sc_hd__mux2_1 _028_ (
    .A0(din0_ext[17]),
    .A1(din0_bist[17]),
    .S(mbist_enable),
    .X(din0_mux[17])
  );
  sky130_fd_sc_hd__mux2_1 _029_ (
    .A0(din0_ext[18]),
    .A1(din0_bist[18]),
    .S(mbist_enable),
    .X(din0_mux[18])
  );
  sky130_fd_sc_hd__mux2_1 _030_ (
    .A0(din0_ext[19]),
    .A1(din0_bist[19]),
    .S(mbist_enable),
    .X(din0_mux[19])
  );
  sky130_fd_sc_hd__mux2_1 _031_ (
    .A0(din0_ext[20]),
    .A1(din0_bist[20]),
    .S(mbist_enable),
    .X(din0_mux[20])
  );
  sky130_fd_sc_hd__mux2_1 _032_ (
    .A0(din0_ext[21]),
    .A1(din0_bist[21]),
    .S(mbist_enable),
    .X(din0_mux[21])
  );
  sky130_fd_sc_hd__mux2_1 _033_ (
    .A0(din0_ext[22]),
    .A1(din0_bist[22]),
    .S(mbist_enable),
    .X(din0_mux[22])
  );
  sky130_fd_sc_hd__mux2_1 _034_ (
    .A0(din0_ext[23]),
    .A1(din0_bist[23]),
    .S(mbist_enable),
    .X(din0_mux[23])
  );
  sky130_fd_sc_hd__mux2_1 _035_ (
    .A0(din0_ext[24]),
    .A1(din0_bist[24]),
    .S(mbist_enable),
    .X(din0_mux[24])
  );
  sky130_fd_sc_hd__mux2_1 _036_ (
    .A0(din0_ext[25]),
    .A1(din0_bist[25]),
    .S(mbist_enable),
    .X(din0_mux[25])
  );
  sky130_fd_sc_hd__mux2_1 _037_ (
    .A0(din0_ext[26]),
    .A1(din0_bist[26]),
    .S(mbist_enable),
    .X(din0_mux[26])
  );
  sky130_fd_sc_hd__mux2_1 _038_ (
    .A0(din0_ext[27]),
    .A1(din0_bist[27]),
    .S(mbist_enable),
    .X(din0_mux[27])
  );
  sky130_fd_sc_hd__mux2_1 _039_ (
    .A0(din0_ext[28]),
    .A1(din0_bist[28]),
    .S(mbist_enable),
    .X(din0_mux[28])
  );
  sky130_fd_sc_hd__mux2_1 _040_ (
    .A0(din0_ext[29]),
    .A1(din0_bist[29]),
    .S(mbist_enable),
    .X(din0_mux[29])
  );
  sky130_fd_sc_hd__mux2_1 _041_ (
    .A0(din0_ext[30]),
    .A1(din0_bist[30]),
    .S(mbist_enable),
    .X(din0_mux[30])
  );
  sky130_fd_sc_hd__mux2_1 _042_ (
    .A0(din0_ext[31]),
    .A1(din0_bist[31]),
    .S(mbist_enable),
    .X(din0_mux[31])
  );
  sky130_fd_sc_hd__dfrtp_1 _043_ (
    .CLK(clk),
    .D(mbist_enable),
    .Q(wcr_out[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _044_ (
    .CLK(clk),
    .D(start_bist),
    .Q(wcr_out[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _045_ (
    .CLK(clk),
    .D(bist_done),
    .Q(wcr_out[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _046_ (
    .CLK(clk),
    .D(bist_pass),
    .Q(wcr_out[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _047_ (
    .CLK(clk),
    .D(wcr_out[4]),
    .Q(wcr_out[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _048_ (
    .CLK(clk),
    .D(wcr_out[5]),
    .Q(wcr_out[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _049_ (
    .CLK(clk),
    .D(wcr_out[6]),
    .Q(wcr_out[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _050_ (
    .CLK(clk),
    .D(wcr_out[7]),
    .Q(wcr_out[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _051_ (
    .CLK(clk),
    .D(dout0_sram[0]),
    .Q(wdr_out[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _052_ (
    .CLK(clk),
    .D(dout0_sram[1]),
    .Q(wdr_out[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _053_ (
    .CLK(clk),
    .D(dout0_sram[2]),
    .Q(wdr_out[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _054_ (
    .CLK(clk),
    .D(dout0_sram[3]),
    .Q(wdr_out[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _055_ (
    .CLK(clk),
    .D(dout0_sram[4]),
    .Q(wdr_out[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _056_ (
    .CLK(clk),
    .D(dout0_sram[5]),
    .Q(wdr_out[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _057_ (
    .CLK(clk),
    .D(dout0_sram[6]),
    .Q(wdr_out[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _058_ (
    .CLK(clk),
    .D(dout0_sram[7]),
    .Q(wdr_out[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _059_ (
    .CLK(clk),
    .D(dout0_sram[8]),
    .Q(wdr_out[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _060_ (
    .CLK(clk),
    .D(dout0_sram[9]),
    .Q(wdr_out[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _061_ (
    .CLK(clk),
    .D(dout0_sram[10]),
    .Q(wdr_out[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _062_ (
    .CLK(clk),
    .D(dout0_sram[11]),
    .Q(wdr_out[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _063_ (
    .CLK(clk),
    .D(dout0_sram[12]),
    .Q(wdr_out[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _064_ (
    .CLK(clk),
    .D(dout0_sram[13]),
    .Q(wdr_out[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _065_ (
    .CLK(clk),
    .D(dout0_sram[14]),
    .Q(wdr_out[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _066_ (
    .CLK(clk),
    .D(dout0_sram[15]),
    .Q(wdr_out[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _067_ (
    .CLK(clk),
    .D(dout0_sram[16]),
    .Q(wdr_out[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _068_ (
    .CLK(clk),
    .D(dout0_sram[17]),
    .Q(wdr_out[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _069_ (
    .CLK(clk),
    .D(dout0_sram[18]),
    .Q(wdr_out[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _070_ (
    .CLK(clk),
    .D(dout0_sram[19]),
    .Q(wdr_out[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _071_ (
    .CLK(clk),
    .D(dout0_sram[20]),
    .Q(wdr_out[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _072_ (
    .CLK(clk),
    .D(dout0_sram[21]),
    .Q(wdr_out[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _073_ (
    .CLK(clk),
    .D(dout0_sram[22]),
    .Q(wdr_out[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _074_ (
    .CLK(clk),
    .D(dout0_sram[23]),
    .Q(wdr_out[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _075_ (
    .CLK(clk),
    .D(dout0_sram[24]),
    .Q(wdr_out[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _076_ (
    .CLK(clk),
    .D(dout0_sram[25]),
    .Q(wdr_out[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _077_ (
    .CLK(clk),
    .D(dout0_sram[26]),
    .Q(wdr_out[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _078_ (
    .CLK(clk),
    .D(dout0_sram[27]),
    .Q(wdr_out[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _079_ (
    .CLK(clk),
    .D(dout0_sram[28]),
    .Q(wdr_out[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _080_ (
    .CLK(clk),
    .D(dout0_sram[29]),
    .Q(wdr_out[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _081_ (
    .CLK(clk),
    .D(dout0_sram[30]),
    .Q(wdr_out[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _082_ (
    .CLK(clk),
    .D(dout0_sram[31]),
    .Q(wdr_out[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _083_ (
    .CLK(clk),
    .D(din0_mux[0]),
    .Q(wbr[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _084_ (
    .CLK(clk),
    .D(din0_mux[1]),
    .Q(wbr[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _085_ (
    .CLK(clk),
    .D(din0_mux[2]),
    .Q(wbr[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _086_ (
    .CLK(clk),
    .D(din0_mux[3]),
    .Q(wbr[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _087_ (
    .CLK(clk),
    .D(din0_mux[4]),
    .Q(wbr[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _088_ (
    .CLK(clk),
    .D(din0_mux[5]),
    .Q(wbr[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _089_ (
    .CLK(clk),
    .D(din0_mux[6]),
    .Q(wbr[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _090_ (
    .CLK(clk),
    .D(din0_mux[7]),
    .Q(wbr[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _091_ (
    .CLK(clk),
    .D(din0_mux[8]),
    .Q(wbr[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _092_ (
    .CLK(clk),
    .D(din0_mux[9]),
    .Q(wbr[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _093_ (
    .CLK(clk),
    .D(din0_mux[10]),
    .Q(wbr[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _094_ (
    .CLK(clk),
    .D(din0_mux[11]),
    .Q(wbr[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _095_ (
    .CLK(clk),
    .D(din0_mux[12]),
    .Q(wbr[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _096_ (
    .CLK(clk),
    .D(din0_mux[13]),
    .Q(wbr[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _097_ (
    .CLK(clk),
    .D(din0_mux[14]),
    .Q(wbr[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _098_ (
    .CLK(clk),
    .D(din0_mux[15]),
    .Q(wbr[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _099_ (
    .CLK(clk),
    .D(din0_mux[16]),
    .Q(wbr[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _100_ (
    .CLK(clk),
    .D(din0_mux[17]),
    .Q(wbr[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _101_ (
    .CLK(clk),
    .D(din0_mux[18]),
    .Q(wbr[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _102_ (
    .CLK(clk),
    .D(din0_mux[19]),
    .Q(wbr[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _103_ (
    .CLK(clk),
    .D(din0_mux[20]),
    .Q(wbr[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _104_ (
    .CLK(clk),
    .D(din0_mux[21]),
    .Q(wbr[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _105_ (
    .CLK(clk),
    .D(din0_mux[22]),
    .Q(wbr[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _106_ (
    .CLK(clk),
    .D(din0_mux[23]),
    .Q(wbr[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _107_ (
    .CLK(clk),
    .D(din0_mux[24]),
    .Q(wbr[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _108_ (
    .CLK(clk),
    .D(din0_mux[25]),
    .Q(wbr[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _109_ (
    .CLK(clk),
    .D(din0_mux[26]),
    .Q(wbr[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _110_ (
    .CLK(clk),
    .D(din0_mux[27]),
    .Q(wbr[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _111_ (
    .CLK(clk),
    .D(din0_mux[28]),
    .Q(wbr[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _112_ (
    .CLK(clk),
    .D(din0_mux[29]),
    .Q(wbr[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _113_ (
    .CLK(clk),
    .D(din0_mux[30]),
    .Q(wbr[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _114_ (
    .CLK(clk),
    .D(din0_mux[31]),
    .Q(wbr[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _115_ (
    .CLK(clk),
    .D(addr0_mux[0]),
    .Q(wbr[32]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _116_ (
    .CLK(clk),
    .D(addr0_mux[1]),
    .Q(wbr[33]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _117_ (
    .CLK(clk),
    .D(addr0_mux[2]),
    .Q(wbr[34]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _118_ (
    .CLK(clk),
    .D(addr0_mux[3]),
    .Q(wbr[35]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _119_ (
    .CLK(clk),
    .D(addr0_mux[4]),
    .Q(wbr[36]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _120_ (
    .CLK(clk),
    .D(addr0_mux[5]),
    .Q(wbr[37]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _121_ (
    .CLK(clk),
    .D(addr0_mux[6]),
    .Q(wbr[38]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _122_ (
    .CLK(clk),
    .D(addr0_mux[7]),
    .Q(wbr[39]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _123_ (
    .CLK(clk),
    .D(addr0_mux[8]),
    .Q(wbr[40]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _124_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[41]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _125_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[42]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _126_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[43]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _127_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[44]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _128_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[45]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _129_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[46]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _130_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[47]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _131_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[48]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _132_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[49]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _133_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[50]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _134_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[51]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _135_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[52]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _136_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[53]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _137_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[54]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _138_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[55]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _139_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[56]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _140_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[57]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _141_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[58]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _142_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[59]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _143_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[60]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _144_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[61]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _145_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[62]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _146_ (
    .CLK(clk),
    .D(1'h0),
    .Q(wbr[63]),
    .RESET_B(rst_n)
  );
  \$paramod$1285c1740f954ea74f58bd88e5bc92df4339bc55\MBIST_Controller  u_mbist (
    .addr0(addr0_bist),
    .bist_done(bist_done),
    .bist_pass(bist_pass),
    .clk(clk),
    .csb0(csb0_bist),
    .din0(din0_bist),
    .dout0(dout0_sram),
    .rst_n(rst_n),
    .start_bist(start_bist),
    .web0(web0_bist)
  );
  sram_32_512_sky130A u_sram (
    .addr0(addr0_mux),
    .clk0(clk),
    .csb0(csb0_mux),
    .din0(din0_mux),
    .dout0(dout0_sram),
    .web0(web0_mux)
  );
  assign dout0_ext = dout0_sram;
endmodule
